server:
  #本服务端口
  port: 9003
spring:
  application:
    #注册到eureka-server的服务名称
    name: ms-eureka-client-9003
eureka:
  client:
    #eureka-server地址
    service-url:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9000/eureka/
  instance:
    #点击具体微服务，右下角显示ip
    prefer-ip-address: true
    #显示的服务名称
    instance-id: ms-eureka-client-9003


